
<%@ Page Language="C#" MasterPageFile="~/MasterPage1.master" AutoEventWireup="true" %>
   
<asp:Content ID="HeadContent" ContentPlaceHolderID="head" runat="server">
    <title>FLL</title>
    <img src="images/fll.png" alt="fll logo" class="logo" />
    <h1 style=font="italic">FIRST LEGO LEAGE</h1>
    <p1>    FIRST LEGO League, also known as FLL, is an international robotics program for young students. It introduces children to science, technology, engineering, and mathematics in a fun and engaging way. In FLL, teams use LEGO components to build robots. These robots are programmed to complete missions on a themed competition field. Each season has a new real-world problem for students to explore. Teams research the problem and create an innovative solution. Programming is done using beginner-friendly visual coding languages. Students learn how sensors, motors, and logic work together. FLL encourages teamwork and collaboration among team members. Every participant has a role, such as programmer, builder, or researcher. The program focuses strongly on problem-solving skills. Students learn to test, fail, and improve their designs. FLL also teaches time management and planning. An important part of FLL is the Core Values, which emphasize respect and cooperation. Teams are judged not only on robot performance but also on teamwork. Competitions are designed to be supportive rather than aggressive. Students present their projects to judges and explain their ideas. This helps improve communication and public speaking skills. Mentors guide teams but do not do the work for them. FLL promotes creativity and critical thinking. Students gain confidence through hands-on learning. The program welcomes beginners with no prior experience. Schools and community groups around the world participate in FLL. The competition season runs for several months each year. Teams attend local and national tournaments. FLL helps students understand how technology impacts society. Many participants develop a long-term interest in STEM. The skills learned in FLL are useful in future studies. The program creates a strong sense of community. Overall, FIRST LEGO League inspires the next generation of innovators.

</asp:Content>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h1>how to create a team</h1>
    <p1>
        To create an FLL team, the first step is to gather a group of students who are interested in robotics and technology. The students must be within the age range defined by FIRST LEGO League. After forming the group, an adult coach should be chosen to guide the team and handle registration. The coach does not need advanced technical knowledge but should be organized and supportive. Next, the team must register on the official FIRST website. Once registration is complete, the team will receive access to the season’s challenge materials. The team should then choose a unique and creative team name. Finding a suitable meeting location, such as a school, library, or community center, is important. After that, the required LEGO robotics kit and programming software should be obtained. The coach should schedule regular practice meetings for the team. During early meetings, students should learn the basics of building and programming the robot. The team should carefully read and analyze the yearly challenge rules. Roles such as builder, programmer, and researcher can be assigned to help organize the work. The robot should be designed to complete as many missions as possible. Testing and improving the robot through repeated trials is essential. At the same time, the team should begin working on the innovation project. This involves identifying a real-world problem related to the challenge theme. Research should be conducted to understand the problem better. The team then develops a creative solution. Students should practice explaining their project clearly. Core values such as teamwork, respect, and inclusion should be followed at all times. The coach should encourage cooperation and positive communication. As the competition approaches, the robot and project should be refined. Practice runs help improve performance and confidence. The team should prepare for judging by rehearsing presentations. On competition day, students demonstrate their work to the judges. Team members should support each other throughout the event. After the competition, the team can reflect on what they learned. Creating an FLL team helps students grow both technically and personally.
        </p1>
        

</asp:Content>
